button_text:
  default: "Image Gallery"
add_images_prompt:
  default: "Add images"
button_icon:
  default: "th"
image_order:
  default: horizontal
  type: enum
  choices:
    - vertical
auto_enabled:
  default: false
auto_images_required:
  default: 3
  min: 1
auto_enabled_categories:
  default: ""
  type: list
  list_type: simple